# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(903, 620)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.casetree = QtGui.QTreeWidget(self.centralwidget)
        self.casetree.setGeometry(QtCore.QRect(0, 0, 411, 531))
        self.casetree.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.casetree.setColumnCount(1)
        self.casetree.setObjectName(_fromUtf8("casetree"))
        self.casetree.headerItem().setText(0, _fromUtf8("测试用例树"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(420, 0, 471, 161))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(170, 90, 81, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.ip = QtGui.QLineEdit(self.groupBox)
        self.ip.setGeometry(QtCore.QRect(280, 90, 111, 20))
        self.ip.setObjectName(_fromUtf8("ip"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 90, 61, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 120, 71, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.atten_COM = QtGui.QComboBox(self.groupBox)
        self.atten_COM.setGeometry(QtCore.QRect(70, 90, 81, 22))
        self.atten_COM.setObjectName(_fromUtf8("atten_COM"))
        self.atten_COM.addItem(_fromUtf8(""))
        self.atten_COM.addItem(_fromUtf8(""))
        self.atten_COM.addItem(_fromUtf8(""))
        self.atten_COM.addItem(_fromUtf8(""))
        self.atten_COM.addItem(_fromUtf8(""))
        self.atten_COM.addItem(_fromUtf8(""))
        self.atten_COM.addItem(_fromUtf8(""))
        self.atten_COM.addItem(_fromUtf8(""))
        self.atten_COM.addItem(_fromUtf8(""))
        self.atten_COM.addItem(_fromUtf8(""))
        self.atten_COM.addItem(_fromUtf8(""))
        self.atten_COM.addItem(_fromUtf8(""))
        self.product = QtGui.QComboBox(self.groupBox)
        self.product.setGeometry(QtCore.QRect(70, 30, 81, 22))
        self.product.setObjectName(_fromUtf8("product"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 60, 41, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.son_product = QtGui.QComboBox(self.groupBox)
        self.son_product.setGeometry(QtCore.QRect(70, 60, 81, 22))
        self.son_product.setObjectName(_fromUtf8("son_product"))
        self.username = QtGui.QLineEdit(self.groupBox)
        self.username.setGeometry(QtCore.QRect(280, 30, 111, 20))
        self.username.setObjectName(_fromUtf8("username"))
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(170, 30, 81, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(170, 60, 81, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.password = QtGui.QLineEdit(self.groupBox)
        self.password.setGeometry(QtCore.QRect(280, 60, 111, 20))
        self.password.setObjectName(_fromUtf8("password"))
        self.exceltoxml = QtGui.QPushButton(self.groupBox)
        self.exceltoxml.setGeometry(QtCore.QRect(170, 120, 61, 23))
        self.exceltoxml.setObjectName(_fromUtf8("exceltoxml"))
        self.py2xml = QtGui.QPushButton(self.groupBox)
        self.py2xml.setGeometry(QtCore.QRect(250, 120, 71, 23))
        self.py2xml.setObjectName(_fromUtf8("py2xml"))
        self.savecfg = QtGui.QPushButton(self.groupBox)
        self.savecfg.setGeometry(QtCore.QRect(340, 120, 71, 23))
        self.savecfg.setObjectName(_fromUtf8("savecfg"))
        self.sship = QtGui.QLineEdit(self.groupBox)
        self.sship.setGeometry(QtCore.QRect(70, 120, 81, 20))
        self.sship.setObjectName(_fromUtf8("sship"))
        self.testlog = QtGui.QTextEdit(self.centralwidget)
        self.testlog.setGeometry(QtCore.QRect(420, 180, 461, 351))
        self.testlog.setObjectName(_fromUtf8("testlog"))
        self.selectall = QtGui.QPushButton(self.centralwidget)
        self.selectall.setGeometry(QtCore.QRect(214, 550, 71, 23))
        self.selectall.setObjectName(_fromUtf8("selectall"))
        self.selectnone = QtGui.QPushButton(self.centralwidget)
        self.selectnone.setGeometry(QtCore.QRect(330, 550, 71, 23))
        self.selectnone.setObjectName(_fromUtf8("selectnone"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 550, 81, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.sumtestcases = QtGui.QLabel(self.centralwidget)
        self.sumtestcases.setGeometry(QtCore.QRect(90, 550, 81, 21))
        self.sumtestcases.setText(_fromUtf8(""))
        self.sumtestcases.setObjectName(_fromUtf8("sumtestcases"))
        self.start_test = QtGui.QPushButton(self.centralwidget)
        self.start_test.setGeometry(QtCore.QRect(474, 550, 61, 23))
        self.start_test.setObjectName(_fromUtf8("start_test"))
        self.casetree.raise_()
        self.testlog.raise_()
        self.groupBox.raise_()
        self.selectall.raise_()
        self.selectnone.raise_()
        self.label_10.raise_()
        self.sumtestcases.raise_()
        self.start_test.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_save = QtGui.QAction(MainWindow)
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_open = QtGui.QAction(MainWindow)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.menu.addAction(self.action_save)
        self.menu.addAction(self.action_open)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "基本配置", None))
        self.label_6.setText(_translate("MainWindow", "DUT 登陆地址", None))
        self.ip.setText(_translate("MainWindow", "192.168.0.1", None))
        self.label_9.setText(_translate("MainWindow", "产品类", None))
        self.label_13.setText(_translate("MainWindow", "产品COM", None))
        self.label_14.setText(_translate("MainWindow", "Ssh地址", None))
        self.atten_COM.setItemText(0, _translate("MainWindow", "COM1", None))
        self.atten_COM.setItemText(1, _translate("MainWindow", "COM2", None))
        self.atten_COM.setItemText(2, _translate("MainWindow", "COM3", None))
        self.atten_COM.setItemText(3, _translate("MainWindow", "COM4", None))
        self.atten_COM.setItemText(4, _translate("MainWindow", "COM5", None))
        self.atten_COM.setItemText(5, _translate("MainWindow", "COM6", None))
        self.atten_COM.setItemText(6, _translate("MainWindow", "COM7", None))
        self.atten_COM.setItemText(7, _translate("MainWindow", "COM8", None))
        self.atten_COM.setItemText(8, _translate("MainWindow", "COM9", None))
        self.atten_COM.setItemText(9, _translate("MainWindow", "COM10", None))
        self.atten_COM.setItemText(10, _translate("MainWindow", "COM11", None))
        self.atten_COM.setItemText(11, _translate("MainWindow", "COM12", None))
        self.label_15.setText(_translate("MainWindow", "产品名", None))
        self.username.setText(_translate("MainWindow", "admin", None))
        self.label_17.setText(_translate("MainWindow", "DUT登陆用户名", None))
        self.label_18.setText(_translate("MainWindow", "DUT 登陆密码", None))
        self.password.setText(_translate("MainWindow", "admin", None))
        self.exceltoxml.setText(_translate("MainWindow", "用例转换", None))
        self.py2xml.setText(_translate("MainWindow", "创建配置", None))
        self.savecfg.setText(_translate("MainWindow", "保存配置", None))
        self.sship.setText(_translate("MainWindow", "192.168.20.2", None))
        self.selectall.setText(_translate("MainWindow", "全选", None))
        self.selectnone.setText(_translate("MainWindow", "全否", None))
        self.label_10.setText(_translate("MainWindow", "测试点总计:", None))
        self.start_test.setText(_translate("MainWindow", "开始测试", None))
        self.menu.setTitle(_translate("MainWindow", "文件", None))
        self.action_save.setText(_translate("MainWindow", "保存", None))
        self.action_open.setText(_translate("MainWindow", "打开", None))

